on:
  push:
    tags:
      - "v*"
name: gh-pages-release
jobs:
  github-release:
    if: github.repository == 'snomiao/rime-snomiao'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # Github release with changelog
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: npx -y -- github-release-from-cc-changelog ${{ env.RELEASE_VERSION }}
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # pack
      - run: mkdir -p ./rime-snomiao-${{ env.RELEASE_VERSION }}
      - run: cp -r Rime/* *.md ./rime-snomiao-${{ env.RELEASE_VERSION }}
      - run: zip -r rime-snomiao-${{ env.RELEASE_VERSION }}.zip ./rime-snomiao-${{ env.RELEASE_VERSION }} -UN=UTF8
      # upload
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: rime-snomiao-${{ env.RELEASE_VERSION }}.zip
          tag: ${{ github.ref }}
      # push to gh pages
      - run: cp rime-snomiao-${{ env.RELEASE_VERSION }}.zip docs/rime-snomiao-${{ env.RELEASE_VERSION }}.zip
      - run: cp rime-snomiao-${{ env.RELEASE_VERSION }}.zip docs/rime-snomiao-latest.zip
      - run: cp CHANGELOG.md docs/CHANGELOG.md
      - run: cp README.md docs/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: true
