name: npm-publish
on:
  push:
    branches:
      - main
jobs:
  release:
    if: github.repository == 'snomiao/rime-snomiao'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: npx semantic-release
