name: npm-publish
on:
  - push
jobs:
  semantic:
    if: github.repository == 'snomiao/rime-snomiao'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # pnpm install
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      # npm publish
      - run: npx semantic-release
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
